import or1 from "../Assets/Images/orient 1.jpg"
import cp from "../Assets/Images/cp.jpg"
import cf from "../Assets/Images/cp_cafe.webp"
// export const places = [
//   {
//     "id": 1,
//     "title": "Café Runway1",
//     "type":"cafe",
//     "description": "A unique aviation-themed café located in Metro Walk, offering a delightful menu of global cuisine, refreshing beverages, and an exciting dining experience inside an airplane.",
//     "rank": "#15 of 2,400 Restaurants in Delhi",
//     "price": 500,
//     "cuisine": "Multi-Cuisine, Vegetarian Friendly, Vegan Options",
//     "specialDiets": ["Vegetarian Friendly", "Vegan Options", "Gluten Free Options"],
//     "rating": 4.5,
//     "reviews": 200,
//     "duration": 2,
//     "image": "https://images.unsplash.com/photo-1573497491208-6b1acb260507?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwxfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//     "images": [
//       "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwyfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//       "https://images.unsplash.com/photo-1543342385-d28383d7c77d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//     ],
//     "contact": "+91 91234 56789",
//     "website": "https://caferunway1.com",
//     "location": "New Delhi",
//     "timings": "Open Now 11:00 am - 11:00 pm",
//     "highlights": [
//       "Aviation-themed dining",
//       "Outdoor seating",
//       "Pet-friendly",
//       "Kids play area"
//     ],
//     "mapLink": "https://maps.google.com/maps?q=Metro%20Walk%20Rohini%20Delhi&t=&z=13&ie=UTF8&iwloc=&output=embed"  
//   },

//   {
//     "id": 2,
//     "title": "Café Orient Express",
//     "type":"cafe",
//     "description": "A luxurious train-themed café that takes you on a journey through fine dining with a variety of European and Continental dishes.",
//     "rank": "#5 of 12,000 Restaurants in Delhi",
//     "price": 1000,
//     "cuisine": "European, Continental",
//     "specialDiets": ["Vegetarian Friendly", "Gluten Free Options"],
//     "rating": 4.8,
//     "reviews": 250,
//     "duration": 1,
//     "image": "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwxfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//     "images": [
//       "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//       "https://images.unsplash.com/photo-1574664060400-dfdb1b4d7ec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//     ],
//     "contact": "+91 98765 43211",
//     "website": "https://orientexpresscafe.com",
//     "location": "New Delhi",
//     "timings": "Open Now 11:00 am - 10:00 pm",
//     "highlights": ["Fine dining", "Themed restaurant", "Luxurious ambiance"],
//     "mapLink": "https://maps.google.com/maps?q=Connaught%20Place%20Delhi&t=&z=13&ie=UTF8&iwloc=&output=embed"
//   },
  
//   {
//     "id": 3,
//     "title": "Bhaijaanz Restaurant",
//     "type":"cafe",
//     "description": "A Salman Khan-themed restaurant with Bollywood vibes, serving Indian and Mughlai dishes inspired by the superstar.",
//     "rank": "#27 of 5,345 Restaurants in Mumbai",
//     "price": 500,
//     "cuisine": "Indian, Mughlai",
//     "specialDiets": ["Vegetarian Friendly", "Halal"],
//     "rating": 4.4,
//     "reviews": 180,
//     "duration": 2,
//     "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//     "images": [
//       "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//       "https://images.unsplash.com/photo-1568605114967-8130f3a36994?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//     ],
//     "contact": "+91 98765 43212",
//     "website": "https://bhaijaanz.com",
//     "location": "New Delhi",
//     "timings": "Open Now 12:00 pm - 11:00 pm",
//     "highlights": ["Bollywood theme", "Celebrity-inspired décor", "Indian cuisine"],
//     "mapLink": "https://maps.google.com/maps?q=Bandra%20Mumbai&t=&z=13&ie=UTF8&iwloc=&output=embed"
//   }
//   // {
//   //   "id": 4,
//   //   "title": "Cat Café Studio",
//   //   "description": "A cozy space where you can enjoy delicious food while spending time with adoptable cats in a homely, relaxing environment.",
//   //   "rank": "#6 of 5,345 Restaurants in Mumbai",
//   //   "price": "₹200 - ₹1,000",
//   //   "cuisine": "Cafe, Vegetarian Friendly, Vegan Options",
//   //   "specialDiets": ["Vegetarian Friendly", "Vegan Options"],
//   //   "rating": 4.7,
//   //   "reviews": 300,
//   //   "duration": 1.5,
//   //   "image": "https://images.unsplash.com/photo-1597079385658-7a2c278de95e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //   "images": [
//   //     "https://images.unsplash.com/photo-1597079385658-7a2c278de95e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //     "https://images.unsplash.com/photo-1574664060400-dfdb1b4d7ec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//   //   ],
//   //   "contact": "+91 98765 43213",
//   //   "website": "https://catcafestudio.com",
//   //   "locations": ["Versova, Mumbai, India"],
//   //   "timings": "Open Now 10:00 am - 10:00 pm",
//   //   "highlights": ["Pet adoption", "Cat-friendly", "Vegan options"],
//   //   "mapLink": "https://maps.google.com/maps?q=Versova%20Mumbai&t=&z=13&ie=UTF8&iwloc=&output=embed"
//   // },
//   // {
//   //   "id": 5,
//   //   "title": "Gufha Restaurant",
//   //   "description": "A jungle-themed restaurant that offers a unique dining experience with a variety of Indian and Mughlai dishes served in a cave-like ambiance.",
//   //   "rank": "#9 of 8,000 Restaurants in Bangalore",
//   //   "price": "₹700 - ₹2,200",
//   //   "cuisine": "Indian, Mughlai",
//   //   "specialDiets": ["Halal", "Vegetarian Friendly"],
//   //   "rating": 4.5,
//   //   "reviews": 210,
//   //   "duration": 2.5,
//   //   "image": "https://images.unsplash.com/photo-1504468387801-2933a9d48cc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwxfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //   "images": [
//   //     "https://images.unsplash.com/photo-1504468387801-2933a9d48cc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //     "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//   //   ],
//   //   "contact": "+91 98765 43214",
//   //   "website": "https://gufharestaurant.com",
//   //   "locations": ["Jayanagar, Bangalore, India"],
//   //   "timings": "Open Now 12:00 pm - 11:00 pm",
//   //   "highlights": ["Themed restaurant", "Unique ambiance", "Cave dining"],
//   //   "mapLink": "https://maps.google.com/maps?q=Jayanagar%20Bangalore&t=&z=13&ie=UTF8&iwloc=&output=embed"
//   // },
//   // {
//   //   "id": 6,
//   //   "title": "Dyu Art Café",
//   //   "description": "A beautiful café housed in a traditional Bangalore bungalow, offering a relaxing space for art lovers to enjoy coffee and light snacks amidst an artistic atmosphere.",
//   //   "rank": "#15 of 8,000 Restaurants in Bangalore",
//   //   "price": "₹150 - ₹800",
//   //   "cuisine": "Cafe, Continental, Vegetarian Friendly",
//   //   "specialDiets": ["Vegetarian Friendly", "Vegan Options"],
//   //   "rating": 4.7,
//   //   "reviews": 320,
//   //   "duration": 1,
//   //   "image": "https://images.unsplash.com/photo-1590080876934-f5e71284b474?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //   "images": [
//   //     "https://images.unsplash.com/photo-1590080876934-f5e71284b474?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080",
//   //     "https://images.unsplash.com/photo-1541542680-73f3a58ec776?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMzQ2NTB8MHwxfGFsbHwzfHx8fHx8fHwxNjcwOTczNTY4&ixlib=rb-4.0.3&q=80&w=1080"
//   //   ],
//   //   "contact": "+91 98765 43215",
//   //   "website": "https://dyuartcafe.com",
//   //   "locations": ["Koramangala, Bangalore, India"],
//   //   "timings": "Open Now 9:00 am - 10:00 pm",
//   //   "highlights": ["Art gallery", "Calm atmosphere", "Traditional bungalow"],
//   //   "mapLink": "https://maps.google.com/maps?q=Koramangala%20Bangalore&t=&z=13&ie=UTF8&iwloc=&output=embed"
//   // },  

//   // {
//   //   "id": 101,
//   //   "title": "Karan Aujla - It Was All A Dream",
//   //   "description": "An exciting event featuring Karan Aujla, details on the location to be announced soon.",
//   //   "rank": "NA",
//   //   "price": "₹3999 - ₹14999",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "NA",
//   //   "reviews": 0,
//   //   "duration": 4,
//   //   "image": "bang3",
//   //   "images": [],
//   //   "contact": "To be announced soon",
//   //   "website": "N/A",
//   //   "locations": ["To be announced soon"],
//   //   "timings": "N/A",
//   //   "highlights": [],
//   //   "mapLink": "N/A"
//   // },
//   // {
//   //   "id": 102,
//   //   "title": "Imagica Theme & Water Park | Feel the adrenaline rush",
//   //   "description": "Experience thrills and fun at Imagica Theme & Water Park located in Devnhave, Mumbai.",
//   //   "rank": "NA",
//   //   "price": "₹664 - ₹2477",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": 4.6,
//   //   "reviews": 125,
//   //   "duration": 2,
//   //   "image": "mumbai4",
//   //   "images": [],
//   //   "contact": "N/A",
//   //   "website": "N/A",
//   //   "locations": ["Devnhave, Mumbai"],
//   //   "timings": "N/A",
//   //   "highlights": [],
//   //   "mapLink": "N/A"
//   // },
//   // {
//   //   "id": 103,
//   //   "title": "Diwali Bash ft. Parmish Verma and Sunanda Sharma",
//   //   "description": "Join us for a spectacular Diwali Bash featuring Parmish Verma and Sunanda Sharma at World Street by Omaxe.",
//   //   "rank": "NA",
//   //   "price": "₹799 - ₹3499",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "NA",
//   //   "reviews": 0,
//   //   "duration": 2,
//   //   "image": "bash",
//   //   "images": [],
//   //   "contact": "N/A",
//   //   "website": "N/A",
//   //   "locations": ["World Street by Omaxe"],
//   //   "timings": "N/A",
//   //   "highlights": [],
//   //   "mapLink": "N/A"
//   // },

//   // {
//   //   "id": 201,
//   //   "title": "Delhi Darshan Trip",
//   //   "description": "A full-day tour of Delhi covering famous landmarks such as India Gate, Red Fort, Qutub Minar, and more.",
//   //   "rank": "1",
//   //   "price": "₹999 - ₹2999",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.7",
//   //   "duration": 2,
//   //   "reviews": 158,
//   //   "image": "delhi1",
//   //   "images": ["delhi1_1", "delhi1_2", "delhi1_3"],
//   //   "contact": "+91 9876543210",
//   //   "website": "https://delhidarshan.com",
//   //   "locations": ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple"],
//   //   "timings": "9:00 AM - 6:00 PM",
//   //   "highlights": ["Air-conditioned transport", "Expert guide", "Entry tickets included"],
//   //   "mapLink": "https://maps.google.com/?q=Delhi+Darshan"
//   // },
//   // {
//   //   "id": 202,
//   //   "title": "Mumbai City Tour",
//   //   "description": "Explore the vibrant city of Mumbai with visits to Gateway of India, Marine Drive, and other iconic spots.",
//   //   "rank": "2",
//   //   "price": "₹1499 - ₹4999",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.8",
//   //   "reviews": 245,
//   //   "duration": 2,
//   //   "image": "mumbai1",
//   //   "images": ["mumbai1_1", "mumbai1_2", "mumbai1_3"],
//   //   "contact": "+91 9123456789",
//   //   "website": "https://mumbaicitytour.com",
//   //   "locations": ["Gateway of India", "Marine Drive", "Chhatrapati Shivaji Terminus", "Haji Ali Dargah"],
//   //   "timings": "10:00 AM - 7:00 PM",
//   //   "highlights": ["Personalized itinerary", "Comfortable transportation", "Cultural insights"],
//   //   "mapLink": "https://maps.google.com/?q=Mumbai+City+Tour"
//   // },
//   // {
//   //   "id": 203,
//   //   "title": "Skandagiri Trek",
//   //   "description": "A thrilling trek to the top of Skandagiri Hill, offering mesmerizing views and a night-time adventure.",
//   //   "rank": "3",
//   //   "price": "₹799 - ₹2499",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.9",
//   //   "reviews": 96,
//   //   "duration": 2,
//   //   "image": "skandagiri1",
//   //   "images": ["skandagiri1_1", "skandagiri1_2", "skandagiri1_3"],
//   //   "contact": "+91 9098765432",
//   //   "website": "https://skandagiritrek.com",
//   //   "locations": ["Skandagiri Hill"],
//   //   "timings": "12:00 AM - 7:00 AM",
//   //   "highlights": ["Night trek", "Camping option", "Experienced trek guide"],
//   //   "mapLink": "https://maps.google.com/?q=Skandagiri+Trek"
//   // }, 

//   // {
//   //   "id": 301,
//   //   "title": "EOD Adventure Park",
//   //   "description": "An exciting adventure park in Delhi offering activities like zip-lining, rock climbing, boating, and much more.",
//   //   "rank": "2",
//   //   "price": "₹500 - ₹2000",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.6",
//   //   "reviews": 132,
//   //   "duration": 2,
//   //   "image": "eod1",
//   //   "images": ["eod1_1", "eod1_2", "eod1_3"],
//   //   "contact": "+91 9123456780",
//   //   "website": "https://eodadventurepark.com",
//   //   "locations": ["EOD Adventure Park, Delhi"],
//   //   "timings": "10:00 AM - 7:00 PM",
//   //   "highlights": ["Zip-lining", "Rock climbing", "Boating", "Team-building activities"],
//   //   "mapLink": "https://maps.google.com/?q=EOD+Adventure+Park+Delhi"
//   // },
//   // {
//   //   "id": 302,
//   //   "title": "Imagica Theme and Water Park",
//   //   "description": "A premier destination in Mumbai offering thrilling rides, water slides, and entertainment for all age groups.",
//   //   "rank": "1",
//   //   "price": "₹999 - ₹3999",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.8",
//   //   "reviews": 468,
//   //   "duration": 2,
//   //   "image": "imagica1",
//   //   "images": ["imagica1_1", "imagica1_2", "imagica1_3"],
//   //   "contact": "+91 9988776655",
//   //   "website": "https://www.imagicaaworld.com",
//   //   "locations": ["Imagica Theme Park, Mumbai"],
//   //   "timings": "11:00 AM - 9:00 PM",
//   //   "highlights": ["Thrilling rides", "Water park", "Live entertainment", "Family-friendly"],
//   //   "mapLink": "https://maps.google.com/?q=Imagica+Theme+Park+Mumbai"
//   // },
//   // {
//   //   "id": 303,
//   //   "title": "Wonderla Amusement Park",
//   //   "description": "A top amusement park in Bangalore featuring a variety of rides, a water park, and attractions for thrill-seekers.",
//   //   "rank": "1",
//   //   "price": "₹750 - ₹2500",
//   //   "cuisine": "N/A",
//   //   "specialDiets": [],
//   //   "rating": "4.9",
//   //   "reviews": 512,
//   //   "duration": 2,
//   //   "image": "wonderla1",
//   //   "images": ["wonderla1_1", "wonderla1_2", "wonderla1_3"],
//   //   "contact": "+91 9090909090",
//   //   "website": "https://www.wonderla.com/bangalore",
//   //   "locations": ["Wonderla Amusement Park, Bangalore"],
//   //   "timings": "11:00 AM - 8:00 PM",
//   //   "highlights": ["Water rides", "High-thrill rides", "Wave pool", "Rain disco"],
//   //   "mapLink": "https://maps.google.com/?q=Wonderla+Bangalore"
//   // }  
// ]


export const places = [
    {
      id: 1,
      title: "Orient Cafe",
      type: "cafe",
      location: "New Delhi",
      description: "A contemporary café offering vegetarian and vegan-friendly options.",
      price: 500,
      duration: 2, // hours
      image: `${or1}`,
    },
    {
      id: 2,
      title: "Lotus Temple",
      type: "activity",
      location: "New Delhi",
      description: "A peaceful visit to the architectural beauty of Lotus Temple.",
      price: 0,
      duration: 1.5, // hours
      image: "https://example.com/lotus-temple.jpg",
    },
    {
      id: 3,
      title: "Central Park Walk",
      type: "activity",
      location: "New Delhi",
      description: "Take a calming walk through the lush green Central Park.",
      price: 0,
      duration: 1, // hours
      image: `${cp}`,
    },
    {
      id: 4,
      title: "Connaught Place Café Tour",
      type: "activity",
      location: "New Delhi",
      description: "Explore a variety of cafés in the heart of Connaught Place.",
      price: 700,
      duration: 3, // hours
      image: `${cf}`,
    },
    // Add more places here as needed
  ];